#!/usr/bin/env bash
# Get the current battery.
set -xeuo pipefail

function main {
    if _has_battery; then
        local battery
        battery="$(_get_battery)"
        _print_percentage "${battery}"
    else
        exit 1
    fi
}

function _has_battery {
    compgen -G "/sys/class/power_supply/BAT*" > /dev/null
}

function _get_battery {
    local bat_path capacity
    bat_path=$(compgen -G "/sys/class/power_supply/BAT*" | head -n1)
    capacity=$(<"${bat_path}/capacity")
    echo "${capacity}"
}

function _print_percentage {
    local percentage
    percentage="$1"

    local color exit_code
    if (( percentage < 30 )); then
        if (( percentage < 10 )); then
            color="#FF0000"
            exit_code=33
        else
            color="#FFFC00"
            exit_code=0
        fi
    else
        color=""
        exit_code=0
    fi

    echo "${percentage}%"
    if [[ -n "${color}" ]]; then
        echo "${percentage}%"
        echo "${color}"
    fi

    exit "${exit_code}"
}

main
