#!/usr/bin/env bash
# Get the CPU temperature.
set -xeuo pipefail

function main {
    local temperature
    temperature="$(_get_temperature)"
    if [[ -n "${temperature}" ]]; then
        _print_temperature "${temperature}"
    else
        exit 1
    fi
}

function _get_temperature {
    local name
    for hwmon in /sys/class/hwmon/hwmon*; do
        name="$(cat "${hwmon}/name" 2>/dev/null)"
        case "${name}" in
            k10temp|zenpower|coretemp)
                local temperature
                temperature=$(cat "${hwmon}/temp1_input" 2>/dev/null)
                if [[ "${temperature}" =~ ^[0-9]+$ ]]; then
                    echo "$(( temperature / 1000 ))"
                    return
                fi
            ;;
        esac
    done
}

function _print_temperature {
    local temperature
    temperature="$1"

    local color exit_code
    if (( temperature > 60 )); then
        if (( temperature > 80 )); then
            color="#FF0000"
            exit_code=33
        else
            color="#FFFC00"
            exit_code=0
        fi
    else
        color=""
        exit_code=0
    fi

    echo "${temperature}º"
    if [[ -n "${color}" ]]; then
        echo "${temperature}º"
        echo "${color}"
    fi

    exit "${exit_code}"
}

main
