#!/usr/bin/env bash
# Show the power menu.

declare -A _OPTIONS=(
    [lock]="Lock"
    [reboot]="Reboot"
    [shutdown]="Shutdown"
)

function main {
    local selected_option
    selected_option="$(_render_menu)"
    _take_action "${selected_option}"
}

function _render_menu {
    menu_options="${_OPTIONS[lock]}\n${_OPTIONS[reboot]}\n${_OPTIONS[shutdown]}"
    selected_option="$(
        echo -e "${menu_options}" \
        | rofi -dmenu -i -config "${HOME}/.config/rofi/rofidmenu.rasi"
    )"
    echo "${selected_option}"
}

function _take_action {
    local selected_option
    selected_option="$1"

    if [[ -z "${selected_option}" ]]; then
        return
    fi

    case "${selected_option}" in
        "${_OPTIONS[lock]}")
            local wallpaper temp_picture resolution
            wallpaper="$(cat "${HOME}/.cache/wal/wal")"
            temp_picture=/tmp/i3lock.png
            resolution="$(xrandr | awk '/\*/ {print $1; exit}')"
            magick \
            "${wallpaper}" \
            -resize "${resolution}^" \
            -gravity center \
            -extent "${resolution}" \
            -blur 5x4 \
            "${temp_picture}"
            i3lock "--image=${temp_picture}"
            shred "${temp_picture}"
            rm "${temp_picture}"
        ;;
        "${_OPTIONS[reboot]}")
            systemctl reboot
        ;;
        "${_OPTIONS[shutdown]}")
            systemctl poweroff
        ;;
    esac
}

main
