#!/usr/bin/env bash
# Handle volume.
#
# Args:
#   $1 (optional): Action to perform.
#		Choices:
#			--show (default): Show current volume.
#	   		--up: Increase volume.
#	   		--down: Decrease volume.
#	   		--mute: Mute/Unmute the volume.
set -xeuo pipefail

function main {
    local action
    action="$1"

    local current_volume
    current_volume="$(_get_current_volume)"
    if [[ "${action}" == "--show" ]]; then
        _print_volume "${current_volume}"
    else
        local new_volume
        _do_action "${action}" "${current_volume}"
        new_volume="$(_get_current_volume)"
        _send_notification "${new_volume}"
    fi
}

function _get_current_volume {
    local is_muted
    is_muted="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '/Mute/ {print $2}')"
    if [[ "${is_muted}" == "yes" ]]; then
        echo "0"
    else
        pactl get-sink-volume @DEFAULT_SINK@ | grep -Po "[0-9]{1,3}(?=%)" | head -1
    fi
}

function _print_volume {
    local volume
    volume="$1"
    echo "${volume}%"
}

function _do_action {
    local action volume
    action="$1"
    volume="$2"
    case "${action}" in
        --up)
            pactl set-sink-mute @DEFAULT_SINK@ 0
            if [[ $volume -ge 95 ]]; then
                pactl set-sink-volume @DEFAULT_SINK@ 100%
            else
                pactl set-sink-volume @DEFAULT_SINK@ +5%
            fi
        ;;
        --down)
            pactl set-sink-mute @DEFAULT_SINK@ 0
            pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
        --mute)
            pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
    esac
}

function _send_notification {
    local volume
    volume="$1"
    notify-send --replace-id=1 --app-name=Volume "--hint=int:value:${volume}" "Volume: ${volume}%"
}

main "$@"
