# Github Super-linter for develop branch


name: Super-Linter [develop]

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  super-linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
