# Github Super-linter for master branch


name: Super-Linter [master]

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  super-linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v2.1.0
