# Github Super-linter for master branch


name: Super-Linter [master]

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  super-linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v2.1.0

      # Shellcheck

      - name: shellcheck for .zshrc
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          # .zshrc includes Programs/.programsrc, Workspaces/.hrc and Workspaces/.jrc
          pattern: ".zshrc"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}

      - name: shellcheck for .profile
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: ".profile"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}

      - name: shellcheck for .local/bin/change-brackground
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: "change-background"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}

      - name: shellcheck for .local/bin/sleep-monitor
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: "sleep-monitor"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}

      - name: shellcheck for .local/bin/start-script
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: "start-script"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
